name: "Test change detection"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  get-versions:
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.get-versions.outputs.current }}
      target: ${{ steps.get-versions.outputs.target }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
 
      - name: Get version
        id: get-versions
        run: |
          CURRENT="$(git show main:VERSION)"
          TARGET="$(cat VERSION)"          
          echo "::set-output name=target::v${TARGET}"
          echo "::set-output name=current::v${CURRENT}"

  changes:
    needs: get-versions
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-versions.outputs.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanity test
        run: |
          echo "Current is ${{ needs.get-versions.outputs.current }}"
          echo "Target is ${{ needs.get-versions.outputs.target }}"

      - uses: cds-snc/paths-filter@6a46d6ba2334bcb1cd4a52e4e9a043a59fb6b855 # latest
        id: filter
        with:
          ref: ${{ needs.get-versions.outputs.target }}
          base: ${{ needs.get-versions.outputs.current }}
          filters: |
            readme:
              - 'README.md'

      - name: Changes?
        if: ${{ steps.filter.outputs.readme == 'true' }}
        run: echo "README.md changed"
